import { v4 as uuidv4 } from "uuid";
export const initialExpenses = [
  {
    id: "4",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "1",
    quantity: 500,
    category: "Zakupy",
    groupCategory: "Jedzenie",
    title: "Zakupy Biedronka",
    type: "Wydatek",
  },
  {
    id: "5",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "1",
    quantity: 200,
    category: "Zakupy",
    groupCategory: "Chemia",
    title: "Zakupy Rossman",
    type: "Wydatek",
  },
  {
    id: "6",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "2",
    quantity: 200,
    category: "Podróże",
    groupCategory: "Góry",
    title: "Góry Sowie",
    type: "Wydatek",
  },
  {
    id: "7",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "3",
    quantity: 1500,
    category: "Kredyt",
    groupCategory: "Kredyt hipoteczny",
    title: "Nasze mieszkanie",
    type: "Wydatek",
  },
  {
    id: "8",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "1",
    quantity: 700,
    category: "Zakupy",
    groupCategory: "Jedzenie",
    title: "Zakupy Lidl",
    type: "Wydatek",
  },
  {
    id: "9",
    user_id: "1",
    date: "13.09.2020",
    idAccount: "2",
    quantity: 50,
    category: "Zakupy",
    groupCategory: "Jedzenie",
    title: "Zakupy City",
    type: "Wydatek",
  },
  {
    id: "10",
    user_id: "1",
    date: "13.09.2020",
    idAccount: "2",
    quantity: 250,
    category: "Kredyt",
    groupCategory: "Termomix",
    title: "Rata",
    type: "Wydatek",
  },
];
