import { v4 as uuidv4 } from "uuid";
export const initialExpenses = [
  {
    id: "4",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "1",
    quantity: 500,
    category: "Zakupy",
    groupCategory: "Jedzenie",
    title: "Zakupy Biedronka",
  },
  {
    id: "5",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "1",
    quantity: 200,
    category: "Zakupy",
    groupCategory: "Chemia",
    title: "Zakupy Rossman",
  },
  {
    id: "6",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "2",
    quantity: 200,
    category: "Podróże",
    groupCategory: "",
    title: "Góry Sowie",
  },
  {
    id: "7",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "3",
    quantity: 1500,
    category: "Kredyt",
    groupCategory: "Kredyt hipoteczny",
    title: "Nasze mieszkanie",
  },
  {
    id: "8",
    user_id: "1",
    date: "01.09.2020",
    idAccount: "1",
    quantity: 700,
    category: "Zakupy",
    groupCategory: "Jedzenie",
    title: "Zakupy Lidl",
  },
];
